COLUMNS:
  nam: string
  Price: string
  Year: int64
  Millage: string
  Fuel: string
  Transmission: string
  Province: string
  Color: string
  Engine Capacity: string
  Body Type: string
  Ad Reference: string
  Features: string
  Owner nam: string
  url: string

TARGET_COLUMN:
  name: Year
